### ISSUE TITLE
[help wanted] Error exec lua-ts function lua_sched

### ISSUE THREAD

**Issue by WuShaoling** [hypertrons/hypertrons#261]
When I start the application, the log output is as follows. 

![image](https://user-images.githubusercontent.com/16188599/74899819-dfbd7c00-53d8-11ea-8961-0602961be366.png)

Is there a component configuration error or is there a bug in the application?

**Comment by frank-zsy** [comment]
What's the problem here?

**Comment by WuShaoling** [comment]
> What's the problem here?

I updated the configuration and the problem persists.

**Comment by WuShaoling** [comment]
![image](https://user-images.githubusercontent.com/16188599/74900216-08924100-53da-11ea-9adf-17739e09651c.png)

**Comment by WuShaoling** [comment]
There may be a problem with the issue_reminder component, I am checking this component.
