### ISSUE TITLE
[Doc] Improve contributing guide

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons#268]
We need to improve contributing guide to be more detailed, can refer to https://github.com/wuhan2020/wuhan2020/blob/master/CONTRIBUTING.md

But maybe we don't need screen shot for illustration, ASCII art is preferred.

**Comment by frank-zsy** [comment]
@heming6666 After improving the guide, you may also add component to generate contributing guide to existing repo by committing the template to a new branch. I may start a new issue to track this.

**Comment by heming6666** [comment]
> @heming6666 After improving the guide, you may also add component to generate contributing guide to existing repo by committing the template to a new branch. I may start a new issue to track this.

ok.
