### ISSUE TITLE
[Bug] Weekly report was sent without data

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons#272]
This week's weekly report was sent without data in #271 

Need to check out why did this happen.

**Comment by WuShaoling** [comment]
In the weekly-report component, we only gets the data for the previous week, so we need to compare the creation or merge date of the issue or PR，for example:

`app/basic/helper/weekly-report/weekly-report.ts`
```
const newIssue = repoData.issues.filter(issue => issue.createdAt >= lastWeek).length;
```
(There are many similar filters)

the data type of `issue.createdAt` is `string`, and the data type of `lastWeek` is `Date`. The data types of the two are inconsistent, causing the filter to fail.

In the definition of issue, the type of createdAt is `Date`, it is not known why the type changed from `Date` to `string`.

**Comment by frank-zsy** [comment]
@WuShaoling So it seems that this is not a weekly report issue, this is a repo data issue, can you continue look into this.
