### ISSUE TITLE
[Feature] We need a component to generate contributing guide template

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons#274]
We may need a component to auto generate contributing guide template to help new projects to setup their contributing guide.

This feature will involve new API for hosting platform client, we may add `updateFile(path: string, content: string, branch: string)` to commit the file content to a new branch on the project, so other developers can edit the file on the new branch and merge it to main branch later.

**Comment by liwen-tj** [comment]
I can't find new branch api in Octokit. 
Is it reasonable If I create a new pull request to auto generate contributing guide template?

**Comment by liwen-tj** [comment]
Or I use [github ref api ](https://developer.github.com/v3/git/refs/)?

**Comment by frank-zsy** [comment]
There should be API for new branch and then start a pull request from that branch to the main branch, the API above looks like good.

**Comment by frank-zsy** [comment]
What is the development process of this issue now? @liwen-tj

**Comment by liwen-tj** [comment]
Please help review the code.
