### ISSUE TITLE
[Feature] We may need to extract the common CI checks

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons#277]
For `license header check`, `markdown lint` and `file name check`, now we implement in the project, but actually we can extract all these checks into a single repo and make an image for CI, so every repo can use the image to check these things in CI.

**Comment by frank-zsy** [comment]
It should be considered that if we use CI image to run CI in actions, how can we can the checks in local development env?

**Comment by WuShaoling** [comment]
Resolved by #287.
