### ISSUE TITLE
[bug] Can not update remote configuration

### ISSUE THREAD

**Issue by heming6666** [hypertrons/hypertrons#306]
I tried to make some changes to the remote configuration in `hypertrons.json`, but it seems that it doesn't take effect.

- Repository for test ： https://github.com/heming6666/bot-test
- Issue for test : https://github.com/heming6666/bot-test/issues/34

As is explained in the issue [heming6666/bot-test/issues/34](https://github.com/heming6666/bot-test/issues/34), I removed `auto-label` and `self-assign` component in `hypertrons.json` via [this commit](https://github.com/heming6666/bot-test/commit/3d451ff940d18ff6d12236013e2369eba7a49743) , but the labels were still added automatically by menbotics and I can still assign myself by entering `self-assign` command.

Is there anything that I'm possibly missing? @WuShaoling 

Thanks!

**Comment by frank-zsy** [comment]
@menbotics really acts weird recent days, we need to checkout what is going wrong here. The fundamental functions should be very solid and reliable.

**Comment by frank-zsy** [comment]
@GoodMeowing Maybe you can share about the git history part on today's meeting? Is there any chance that something went wrong on load config history?

**Comment by GoodMeowing** [comment]
> @GoodMeowing Maybe you can share about the git history part on today's meeting? Is there any chance that something went wrong on load config history?

I will share this part today about mechanisms of this feature. A proposal has been added on meeting docs.
Loading components from git history may fail in bad network environment. As for loading more components than required, this may relate to repo component management. I will check it.
