### ISSUE TITLE
[Help] Ubuntu18 Desktop can't run hypertrons.

### ISSUE THREAD

**Issue by liwen-tj** [hypertrons/hypertrons#331]
I can't run hypertrons in windows 10. So I tried to install ubuntu18 desktop. But there is still error when running npm start. Here is logs in common-error.log
`2020-05-29 02:46:40,907 ERROR 17681 [host-github-component-service] Error while load components, e=TypeError: Cannot read property 'file' of undefined
2020-05-29 02:46:40,907 ERROR 17681 [host-github] Sync hosting base components data error!`

Anyone can help?

**Comment by GoodMeowing** [comment]
Do you set `installation` config as bellow?

Notify this item: `installation - client - configs - component - file`. It claim the lua service related files. 

``` json
  "installation": {
    "client": {
      "configs": [
        {
          "type": "github",
          "config": {
            "name": "github",
            "endpoint": "https://api.github.com/",
            "appId": 49142,
            "privateKeyPath": "private-key.pem",
            "privateKeyPathAbsolute": false,
            "webhook": {
              "path": "/",
              "secret": "test",
              "proxyUrl": "https://smee.io/7ynZ7HZRRiAcuAx"
            },
            "fetcher": {
              "tokens": [
                "b13ccb7b44bee66a7c3f84806e5a6bf4e22d07d2"
              ]
            },
            "config": {
              "remote": {
                "filePath": ".github/hypertrons.json"
              },
              "private": {
                "file": {
                  "rootPath": "./repo_configs/"
                }
              }
            },
            "component": {
              "file": {
                "basePath": "app/component",
                "configModule": "config",
                "luaModule": "index.lua",
                "versionPath": "version.json"
              }
            }
          }
        }
      ]
    }
  },
```

**Comment by liwen-tj** [comment]
After adding `component` config，there is no more error logs in hypertrons/common-error.log.  But hypertrons seems not work, my repo still can't auto label.

**Comment by GoodMeowing** [comment]
I have a similar problem, maybe it is related to some changes about repo id. After I started hypertrons with configuration locally, I didn't receive the webhook events.

**Comment by liwen-tj** [comment]
Here is error info.
`2020-06-03 19:44:38,440 ERROR 22939 nodejs.HttpError: request to https://api.github.com/repos/liwen-tj/just2test/issues/10/labels failed, reason: connect ECONNREFUSED 13.250.168.23:443
    at /home/liwen/hypertrons/node_modules/@octokit/request/dist-src/fetch-wrapper.js:88:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GitHubClient.addLabels (/home/liwen/hypertrons/app/plugin/github/GitHubClient.ts:202:5)
name: "HttpError"
status: 500
headers: {}
request: {"method":"POST","url":"https://api.github.com/repos/liwen-tj/just2test/issues/10/labels","headers":{"accept":"application/vnd.github.v3+json","user-agent":"octokit.js/16.35.0 Node.js/12.18.0 (Linux 4.15; x64)","authorization":"token [REDACTED]","content-type":"application/json; charset=utf-8"},"body":"{\"labels\":[\"kind/bug\"]}","request":{"validate":{"issue_number":{"required":true,"type":"integer"},"labels":{"required":true,"type":"string[]"},"number":{"alias":"issue_number","deprecated":true,"type":"integer"},"owner":{"required":true,"type":"string"},"repo":{"required":true,"type":"string"}}}}
pid: 22939
hostname: iZ2zebjf3ilh2v36rkj3axZ`

**Comment by liwen-tj** [comment]
Ubuntu18 error info
`2020-06-03 02:26:25,302 ERROR 2625 nodejs.HttpError: request to https://api.github.com/graphql failed, reason: connect ECONNREFUSED 13.250.168.23:443
    at /root/hypertrons/node_modules/@octokit/request/dist-src/fetch-wrapper.js:88:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GitHubClient.initToken (/root/hypertrons/node_modules/github-graphql-v4-client/src/index.ts:111:41)
    at async Promise.all (index 0)
    at GitHubClient.init (/root/hypertrons/node_modules/github-graphql-v4-client/src/index.ts:80:5)
    at DataCat.init (/root/hypertrons/node_modules/github-data-cat/src/data_cat.ts:84:5)
name: "HttpError"
status: 500
headers: {}
request: {"method":"POST","url":"https://api.github.com/graphql","headers":{"accept":"application/vnd.github.v3+json","user-agent":"octokit-graphql.js/4.3.1 Node.js/12.17.0 (Linux 5.3; x64)","authorization":"token [REDACTED]","content-type":"application/json; charset=utf-8"},"body":"{\"query\":\"\\nquery {\\n    \\nrateLimit {\\n    resetAt\\n    remaining\\n}\\n\\n}\\n\"}"}
pid: 2625
hostname: ubuntu

2020-06-03 02:26:25,349 ERROR 2625 nodejs.HttpError: request to https://api.github.com/app/installations failed, reason: connect ECONNREFUSED 13.250.168.23:443
    at /root/hypertrons/node_modules/@octokit/request/dist-src/fetch-wrapper.js:88:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at GitHubApp.getInstalledRepos (/root/hypertrons/app/plugin/github/GitHubApp.ts:65:27)
    at GitHubApp.syncData (/root/hypertrons/app/basic/HostingPlatform/HostingBase.ts:156:19)
name: "HttpError"
status: 500
headers: {}
request: {"method":"GET","url":"https://api.github.com/app/installations","headers":{"accept":"application/vnd.github.machine-man-preview+json","user-agent":"octokit.js/16.35.0 Node.js/12.17.0 (Linux 5.3; x64)","authorization":"Bearer [REDACTED]"},"request":{"validate":{"page":{"type":"integer"},"per_page":{"type":"integer"}}}}
pid: 2625
hostname: ubuntu
`

**Comment by liwen-tj** [comment]
`connect ECONNREFUSED` error has been solved by update github token.
