### ISSUE TITLE
[Vote] Change the time of the weekly meeting

### ISSUE THREAD

**Issue by GoodMeowing** [hypertrons/hypertrons#340]
<!-- hypertronsMetaData: {"choices":["a","b"],"participants":["anyone"],"duration":432000000,"launchTime":1594210724341,"comment_id":655483492} --!>
Because it is on the same day as the allspark meeting, consider delaying the time of the hypertrons meeting by half an hour, or change it directly to the next day.

All meeting participants are welcomed to vote in the comments on this issue. You can use `/vote a` or `/vote b` to choose time.

/start-vote a,b anyone 5d

a - Every Wednesday at 20:00
b - Every Thursday at 19:30

**Comment by heming6666** [comment]
/vote a

Interesting :)

**Comment by GoodMeowing** [comment]
> /vote a
> 
> Interesting :)
> 
> > Error: Sorry currently there is no active vote.

I failed too. We might need to collect opinions in the meeting.

**Comment by GoodMeowing** [comment]
As the vote component has a little problem to count vote result, we will directly ask participants about this topic in the meeting.
