### ISSUE TITLE
[Proposal] Cash reward system for Hypertrons

### ISSUE THREAD

**Issue by frank-zsy** [hypertrons/hypertrons#348]
I propose that we can introduce a cash reward system into Hypertrons development.

The basic idea is that we use activity score to assess the contribution of different developers, we also may use 1 - 5 as the weight factor of `issue comment`, `open issue`, `open pr`, `pr review comment`, `merge pr`, but we may also need to label the issue or pr with `difficulty` label(or other labels) so the difficulty of the issue or pr will be the basic score of the issue or pr.

We may count the activity every month and all developers can share the cash reward by the contribution ratio they made during the last month.

WDYT?

**Comment by heming6666** [comment]
Maybe this can be included in `weekly-report` component or integrated into `hypertrons-crx`.

**Comment by frank-zsy** [comment]
> Maybe this can be included in `weekly-report` component or integrated into `hypertrons-crx`.

`weekly-report` is designed to make a general view of weekly activity, mainly on project level, but this will be focused on developer level, so maybe this should be a new independent component. And we can integrate into `hypertrons-crx` which can show a rank list to encourage developers to contribute.

**Comment by heming6666** [comment]
You're right and it make sense for me. There are many interesting things that we can do with `hypertrons-crx`.

> > Maybe this can be included in `weekly-report` component or integrated into `hypertrons-crx`.
> 
> `weekly-report` is designed to make a general view of weekly activity, mainly on project level, but this will be focused on developer level, so maybe this should be a new independent component. And we can integrate into `hypertrons-crx` which can show a rank list to encourage developers to contribute.

**Comment by frank-zsy** [comment]
> You're right and it make sense for me. There are many interesting things that we can do with `hypertrons-crx`.

Indeed, `hypertrons-crx` is limitless!

**Comment by frank-zsy** [comment]
Closed by XSOSI.
