### ISSUE TITLE
[Proposal] We need add UML markdown file to projects

### ISSUE THREAD

**Issue by WeiZhang418** [hypertrons/hypertrons#366]
We need some PlantUML-like files to be added to a source-code repository for easy cooperation.  How to incorporate those markdown files into a repository?

**Comment by frank-zsy** [comment]
Thanks for using Hypertrons.

Hypertrons supports PlantUML render for GitX platforms. If you install a Hypertrons robot instance on GitHub, you can use URL `api.host.com/umlrenderer/installation/owner/repo?path=file_path.uml` to get a UML image for a certain repo.

If you are from the Open Source Training Camp, then you can use `http://github.zhangqx.com/umlrenderer/github/owner/repo?path=file_path.uml` to get the rendered image, replace `owner`, `repo` and `path` to your own real path.

**Comment by WeiZhang418** [comment]
I got "Client not found" or "PARAM ERROR". For example, my file name is tryuml.uml in my blockchain-tutorial repository. Should I type "http://github.zhangqx.com/umlrenderer/github/WeiZhang418/blockchain-tutorial?path=tryuml.uml" into my browser?

**Comment by frank-zsy** [comment]
The repo must have the GitHub App installed, I assume that you did not install `oss-mentor-bot` on this repo.

**Comment by WeiZhang418** [comment]
All right. After installed oss-mentor-bot on my repo, the pic showed.
